# Transformer + Phoneme (Experiment 9)
# EN: BPE, VI: Phoneme

model:
  name: "transformer"
  embed_dim: 512
  hidden_dim: 512
  encoder_layers: 3
  decoder_layers: 3
  num_layers: 3
  dropout: 0.1
  attention_type: null
  num_heads: 8
  ff_dim: 2048

training:
  batch_size: 8
  num_epochs: 10
  learning_rate: 2e-5
  optimizer: "adamw"
  scheduler: "warmup_cosine"
  clip_grad_norm: 1.0
  warmup_steps: 4000
  eval_every: 1000
  save_every: 5000

data:
  sos_id: 1
  eos_id: 2
  pad_id: 0
  unk_id: 3

  source_level: "bpe"
  target_level: "phoneme"
  tokenizer_type: null

  train_src: "/kaggle/input/phomt/train_end_clean.en"
  train_tgt: "/kaggle/input/phomt/train_end_clean.vi"
  dev_src:   "/kaggle/input/phomt/dev_end_clean.en"
  dev_tgt:   "/kaggle/input/phomt/dev_end_clean.vi"
  test_src:  "/kaggle/input/phomt/test_end_clean.en"
  test_tgt:  "/kaggle/input/phomt/test_end_clean.vi"

  vocab_json_train: "/kaggle/input/phomt/full_vocab.json"
  vocab_json_dev:   "/kaggle/input/phomt/full_vocab.json"
  vocab_json_test:  "/kaggle/input/phomt/full_vocab.json"

  min_count: 3
  vocab_size: 16000
  max_seq_len: 512
  limit_train: 10000

device: "cuda"
seed: 42
